### ISSUE TITLE
Cannot find name "AsyncIterable' 

### ISSUE THREAD

**Issue by Max-ChenFei** [jupyterlab/extension-examples#217]
## Description

```
$ jlpm run build:lib && jlpm run build:labextension
$ tsc
../node_modules/@jupyterlab/services/lib/event/index.d.ts(89,52): error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2018' or later
```

## Reproduce

Just as the steps in the Markdown to build the examples
```
conda env create
conda activate jupyterlab-extension-examples
jlpm
jlpm build-ext
```
## Expected behavior
Please change the targe 2017 to 2018 in `tsconfig.json`

## Context

- Operating System and version: Windows 10 
- JupyterLab version: 
- Node.js: 16.17.1
- Python: 3.11
- Pip 23.0.1

**Comment by krassowski** [comment]
Thanks for opening this issue!

This is a problem with JupyterLab 3.6, also discussed in https://github.com/jupyterlab/jupyterlab/issues/14029. Since you control your extension you can bump target to es2018 (see https://github.com/krassowski/jupyter-resource-usage/commit/64ddb722d250ba7abaa784e6ee81ee724952ee20) and we should update the ES target across this repository too - contributions welcome!

**Comment by Max-ChenFei** [comment]
@krassowski Thanks, show I create a PR for this issue?

**Comment by krassowski** [comment]
Please do :)

**Comment by Max-ChenFei** [comment]
Hi, would you like to update the verison of jupyterlab in the github action?
>https://github.com/jupyterlab/extension-examples/blob/0ce165c4487e9f605e512cd7445e381fe870001b/.github/workflows/main.yml#L101
