### ISSUE TITLE
README instructions need updating

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/extension-examples#270]
The command for installing the template in the README:

`copier https://github.com/jupyterlab/extension-template .`

seems to be broken.

I had to run:

`copier copy https://github.com/jupyterlab/extension-template . --trust`

(The `--trust` was for jinja templates.)

**Comment by jtpio** [comment]
Thanks @psychemedia for reporting.

Probably it's because it was for the previous version 7 of `copier`?

![image](https://github.com/user-attachments/assets/5c855610-8066-410a-a58c-85ee9a23635b)

I guess it would still make sense to update the example to the latest version of `copier`, to align with the extension template: https://github.com/jupyterlab/extension-template

If you would like to open a PR that would be great, thanks!
